<a href="https://colab.research.google.com/github/gorzanskik-ai/intro-to-ann/blob/main/02_basics/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
#skalar
scalar = 3.0
print(scalar)
print(type(scalar))

3.0
<class 'float'>


In [6]:
#wektor
vector = np.array([2, 3, 4, 6])
print(vector)
print(type(vector))
print(vector.ndim) #rząd
print(vector.shape)
print(len(vector))

[2 3 4 6]
<class 'numpy.ndarray'>
1
(4,)
4


In [8]:
#matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(matrix)
print(type(matrix))
print(matrix.shape)
print(len(matrix))
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)
2
int64


In [13]:
#tensor
tensor = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                    [[7, 8, 9],
                    [10, 11, 12]]], dtype='int')

print(tensor)
print(tensor.shape)
print(len(tensor))
print(tensor.dtype)
print(tensor.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
2
int64
3


In [14]:
tensor[0]

array([[1, 2, 3],
       [4, 5, 6]])