<a href="https://colab.research.google.com/github/gorzanskik-ai/intro-to-ann/blob/main/03_keras/02_work_with_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import plotly.express as px

In [ ]:
data = np.random.randn(1000, 150)
labels = np.random.randint(2, size=(1000, 1))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 32)                4832      
                                                                 
 dense_13 (Dense)            (None, 1)                 33        
                                                                 
Total params: 4,865
Trainable params: 4,865
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs=20, batch_size=30)

Epoch 1/20
34/34 [==============================] - 1s 3ms/step - loss: 0.9829 - accuracy: 0.4980
Epoch 2/20
34/34 [==============================] - 0s 3ms/step - loss: 0.7739 - accuracy: 0.5440
Epoch 3/20
34/34 [==============================] - 0s 4ms/step - loss: 0.6782 - accuracy: 0.5960
Epoch 4/20
34/34 [==============================] - 0s 4ms/step - loss: 0.6263 - accuracy: 0.6510
Epoch 5/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5918 - accuracy: 0.6850
Epoch 6/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5597 - accuracy: 0.7240
Epoch 7/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5346 - accuracy: 0.7550
Epoch 8/20
34/34 [==============================] - 0s 2ms/step - loss: 0.5107 - accuracy: 0.7760
Epoch 9/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4878 - accuracy: 0.8000
Epoch 10/20
34/34 [==============================] - 0s 2ms/step - loss: 0.4653 - accuracy: 0.8180
Epoch 11/20
34/34 [

In [ ]:
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(data, labels, epochs=40, batch_size=32, validation_split=0.2, verbose=0)

In [ ]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [ ]:
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(150, )))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(data, labels, epochs=40, batch_size=32, validation_split=0.2, verbose=0)

In [ ]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [ ]:
model.predict(test_data)    #prawdopodobieństwo przynależnośći do danej klasy

array([[0.81757414],
       [0.72545135],
       [0.26216453],
       [0.8335993 ],
       [0.98747885]], dtype=float32)

In [ ]:
test_labels

array([[1],
       [1],
       [0],
       [0],
       [1]])

In [ ]:
#Klasyfikacja wieloklasowa

In [ ]:
data = np.random.randn(1000, 150)
labels = np.random.randint(10, size=(1000, 1))
labels[:5]

array([[5],
       [8],
       [4],
       [8],
       [1]])

In [ ]:
from tensorflow.keras.utils import to_categorical

labels = to_categorical(labels)
labels[:5]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(32, activation='relu', input_shape=(150, )))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2, verbose=0)

In [ ]:
test_data = np.random.randn(10, 150)
model.predict(test_data)

array([[7.2869222e-04, 3.4696445e-02, 8.8266162e-03, 7.0654072e-02,
        3.0434373e-01, 1.0402274e-02, 1.2855259e-01, 2.6073024e-02,
        4.0285486e-01, 1.2867667e-02],
       [8.3187940e-03, 1.2062929e-02, 2.4724256e-02, 2.8957089e-03,
        1.4663784e-02, 5.9683118e-03, 4.6395808e-03, 1.2868614e-03,
        9.2205620e-01, 3.3835934e-03],
       [3.2957560e-01, 4.0808570e-02, 5.2497853e-02, 2.3985286e-01,
        1.0412172e-01, 3.8579561e-02, 3.3271846e-03, 5.3481092e-03,
        1.6534008e-01, 2.0548433e-02],
       [1.5890142e-02, 3.3036206e-02, 3.0928625e-02, 9.9977747e-02,
        2.0225969e-01, 6.9787592e-02, 1.9652501e-01, 2.8477830e-01,
        3.7529338e-02, 2.9287402e-02],
       [2.6252127e-01, 3.6812970e-01, 3.9829141e-03, 9.1634262e-03,
        2.7099092e-02, 1.1600738e-01, 9.4592340e-02, 7.2461145e-04,
        5.7763308e-02, 6.0015928e-02],
       [3.4700918e-01, 5.3984364e-03, 1.3872670e-01, 8.0941074e-02,
        2.0139091e-01, 3.5713159e-02, 1.1299492e-02, 2.31

In [ ]:
#Regresja

In [ ]:
data = np.random.random((1000, 20))
labels = 10 * np.random.random(1000)

In [ ]:
train_X = data[800:]
train_Y = labels[800:]
test_X = data[:200]
test_Y = labels[:200]

In [ ]:
model = Sequential()
model.add(Dense(36, activation='relu', input_shape=(20, )))
model.add(Dense(1))

model.compile(optimizer='adam',
              loss='mae',
              metrics=['mae', 'mse'])
history = model.fit(train_X, train_Y, batch_size=32, epochs=27, validation_split=0.2)

Epoch 1/27
5/5 [==============================] - 1s 40ms/step - loss: 5.0996 - mae: 5.0996 - mse: 33.8822 - val_loss: 5.0949 - val_mae: 5.0949 - val_mse: 33.2777
Epoch 2/27
5/5 [==============================] - 0s 9ms/step - loss: 4.9367 - mae: 4.9367 - mse: 32.2752 - val_loss: 4.9230 - val_mae: 4.9230 - val_mse: 31.5591
Epoch 3/27
5/5 [==============================] - 0s 8ms/step - loss: 4.7765 - mae: 4.7765 - mse: 30.7072 - val_loss: 4.7591 - val_mae: 4.7591 - val_mse: 29.8788
Epoch 4/27
5/5 [==============================] - 0s 9ms/step - loss: 4.6156 - mae: 4.6156 - mse: 29.2028 - val_loss: 4.5911 - val_mae: 4.5911 - val_mse: 28.2141
Epoch 5/27
5/5 [==============================] - 0s 8ms/step - loss: 4.4529 - mae: 4.4529 - mse: 27.6207 - val_loss: 4.4127 - val_mae: 4.4127 - val_mse: 26.5021
Epoch 6/27
5/5 [==============================] - 0s 8ms/step - loss: 4.3008 - mae: 4.3008 - mse: 26.1019 - val_loss: 4.2297 - val_mae: 4.2297 - val_mse: 24.7452
Epoch 7/27
5/5 [===========

In [ ]:
predictions = model.predict(test_X)

In [ ]:
predictions[:5]

array([[4.1222324],
       [4.469258 ],
       [4.7509894],
       [5.3866634],
       [4.867769 ]], dtype=float32)

In [ ]:
test_Y[:5]

array([9.41530516, 8.7291028 , 2.14085032, 4.6650093 , 4.6354645 ])