<a href="https://colab.research.google.com/github/gorzanskik-ai/intro-to-ann/blob/main/03_keras/03_work_with_models_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import plotly.graph_objects as go

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.datasets.mnist import load_data

In [23]:
(X_train, y_train), (X_test, y_test) = load_data()

In [24]:
X_train.shape

(60000, 28, 28)

In [25]:
X_train = X_train / 255.    #standaryzacja
X_test = X_test / 255.

In [26]:
model = Sequential()
model.add(Flatten(input_shape=(28, 28)))
model.add(Dense(units=128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 128)               100480    
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_5 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [27]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [28]:
from tensorflow.keras.utils import to_categorical

y_train = to_categorical(y_train, num_classes=10)
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [29]:
model.fit(X_train, y_train, epochs=50, validation_split=0.2, batch_size=32)

Epoch 1/50
1500/1500 [==============================] - 5s 3ms/step - loss: 0.3287 - accuracy: 0.9045 - val_loss: 0.1610 - val_accuracy: 0.9551
Epoch 2/50
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1635 - accuracy: 0.9529 - val_loss: 0.1240 - val_accuracy: 0.9643
Epoch 3/50
1500/1500 [==============================] - 4s 3ms/step - loss: 0.1191 - accuracy: 0.9642 - val_loss: 0.1038 - val_accuracy: 0.9696
Epoch 4/50
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0986 - accuracy: 0.9704 - val_loss: 0.0900 - val_accuracy: 0.9746
Epoch 5/50
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0827 - accuracy: 0.9736 - val_loss: 0.0867 - val_accuracy: 0.9747
Epoch 6/50
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0718 - accuracy: 0.9771 - val_loss: 0.0869 - val_accuracy: 0.9737
Epoch 7/50
1500/1500 [==============================] - 4s 3ms/step - loss: 0.0630 - accuracy: 0.9806 - val_loss: 0.0883 - val_accuracy:

In [30]:
#Praca z modelem

In [31]:
model.layers

In [32]:
model.inputs

[<KerasTensor: shape=(None, 28, 28) dtype=float32 (created by layer 'flatten_2_input')>]

In [33]:
model.outputs

[<KerasTensor: shape=(None, 10) dtype=float32 (created by layer 'dense_5')>]

In [34]:
model.get_config()

{'layers': [{'class_name': 'InputLayer',
   'config': {'batch_input_shape': (None, 28, 28),
    'dtype': 'float32',
    'name': 'flatten_2_input',
    'ragged': False,
    'sparse': False}},
  {'class_name': 'Flatten',
   'config': {'batch_input_shape': (None, 28, 28),
    'data_format': 'channels_last',
    'dtype': 'float32',
    'name': 'flatten_2',
    'trainable': True}},
  {'class_name': 'Dense',
   'config': {'activation': 'relu',
    'activity_regularizer': None,
    'bias_constraint': None,
    'bias_initializer': {'class_name': 'Zeros', 'config': {}},
    'bias_regularizer': None,
    'dtype': 'float32',
    'kernel_constraint': None,
    'kernel_initializer': {'class_name': 'GlorotUniform',
     'config': {'seed': None}},
    'kernel_regularizer': None,
    'name': 'dense_4',
    'trainable': True,
    'units': 128,
    'use_bias': True}},
  {'class_name': 'Dropout',
   'config': {'dtype': 'float32',
    'name': 'dropout_2',
    'noise_shape': None,
    'rate': 0.2,
    'see

In [35]:
model.get_weights()

[array([[-0.01605611,  0.05176347, -0.06119645, ...,  0.06982153,
         -0.06934368,  0.01869482],
        [ 0.03879058, -0.01342127,  0.01302753, ...,  0.03299186,
          0.0190658 ,  0.04567463],
        [-0.05736506, -0.05428357,  0.01974941, ...,  0.00359163,
          0.03050087, -0.01521582],
        ...,
        [-0.07939757, -0.03583255,  0.05799019, ..., -0.03802397,
         -0.01794648, -0.01585058],
        [-0.03537915,  0.05760265, -0.08005128, ..., -0.03411466,
          0.02269872,  0.00660299],
        [-0.03790521,  0.0126076 , -0.07856823, ...,  0.04414456,
         -0.0296488 , -0.00527121]], dtype=float32),
 array([-0.32896942,  0.00799346, -0.02120932,  0.05573032, -0.07435291,
        -0.22028057, -0.0134428 ,  0.29220754, -0.5791156 , -0.13297395,
        -0.04009558, -0.6961266 ,  0.0287044 ,  0.00273115, -0.1258817 ,
        -0.05104679, -0.35449073,  0.24653697, -0.5035847 , -0.08108937,
        -0.13149676,  0.17414482, -0.21182793, -0.22031687, -0.180

In [37]:
for i in range(4):
    print(model.get_weights()[i].shape)

(784, 128)
(128,)
(128, 10)
(10,)


In [41]:
#zapis konfiguracji modelu do pliku json
#tak samo w przypadku plików yaml
model_json = model.to_json()

In [39]:
model_json

'{"class_name": "Sequential", "config": {"name": "sequential_2", "layers": [{"class_name": "InputLayer", "config": {"batch_input_shape": [null, 28, 28], "dtype": "float32", "sparse": false, "ragged": false, "name": "flatten_2_input"}}, {"class_name": "Flatten", "config": {"name": "flatten_2", "trainable": true, "batch_input_shape": [null, 28, 28], "dtype": "float32", "data_format": "channels_last"}}, {"class_name": "Dense", "config": {"name": "dense_4", "trainable": true, "dtype": "float32", "units": 128, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dropout", "config": {"name": "dropout_2", "trainable": true, "dtype": "float32", "rate": 0.2, "noise_shape": null, "seed": null}}, {"class_name": "Dense", 

In [40]:
#odczyt modelu z pliku json
from tensorflow.keras.models import model_from_json

model2 = model_from_json(model_json)
model2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_2 (Flatten)         (None, 784)               0         
                                                                 
 dense_4 (Dense)             (None, 128)               100480    
                                                                 
 dropout_2 (Dropout)         (None, 128)               0         
                                                                 
 dense_5 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [42]:
#Atrybury warstwy

In [45]:
dense_layer = model.layers[1]

In [46]:
dense_layer.input

<KerasTensor: shape=(None, 784) dtype=float32 (created by layer 'flatten_2')>

In [47]:
dense_layer.input_shape

(None, 784)

In [48]:
dense_layer.output

<KerasTensor: shape=(None, 128) dtype=float32 (created by layer 'dense_4')>

In [50]:
dense_layer.output_shape

(None, 128)

In [49]:
dense_layer.trainable

True